config/routes.rb
Rails.application.routes.draw do
  root "notebooks#index"
  devise_for :users, :paths => 'users'

  resources :users do
    resources :notebooks do
      resources :lists do
      end
      resources :pages do
      end
    end
  end



  get "/test" => 'application#test', as: :test


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

  validates :name, presence: true
  validates :notebook_id, presence: true

  belongs_to :notebook
  has_and_belongs_to_many :pages

end

app/models/notebook.rb
class Notebook < ApplicationRecord

  validates :name, presence: true, uniqueness: true
    
  has_many :lists, dependent: :destroy
  has_many :pages, dependent: :destroy
  belongs_to :user
  
end

app/models/page.rb
class Page < ApplicationRecord

  validates :name, presence: true
  validates :notebook_id, presence: true

  belongs_to :notebook
  has_and_belongs_to_many :lists
end

app/models/user.rb
class User < ApplicationRecord

has_many :notebooks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def test
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_notebook
  respond_to :html, :js, :xml

  def index
    @lists = @notebook.lists.all

    if request.xhr?
      render :json => @lists
    end
  end

  def show
    @list = @notebook.lists.find(params[:id])
    @pages = @list.pages.all

    if request.xhr?
      render :json => @pages
    end
  end

  def new
    @list = @notebook.lists.new
  end

  def create
    @list = @notebook.lists.new(list_params)
    @list.save
    
    if request.xhr?
      render :json => @list
    end
  end

  def destroy
    @list = @notebook.lists.find(params[:id])
    @list.destroy
    
    if request.xhr?
      render :json => @notebook.lists
    end
  end

  def edit
    @list = @notebook.lists.find(params[:id])    
  end

  def update
    @list = @notebook.lists.find(params[:id])
    if @list.update(list_params)
      if request.xhr?
        render :json => @list
      end
    end
  end
end

private

  def list_params
    params.permit(:name, :page_ids => [])
  end

  def set_notebook
    @notebook = Notebook.find(params[:notebook_id])
  end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_user

  def index
    @notebooks = Notebook.all
    @nav = {notebook: nil, list: nil, page: nil}

    if request.xhr?
      render :json => @notebooks
    end
  end

  def show
    @notebook = Notebook.find(params[:id])
    @lists = @notebook.lists.all
    @pages = @notebook.pages.all

    if request.xhr?
      render :json => {lists: @lists, pages: @pages}
    end
  end

  def create
    @notebook = @user.notebooks.new(notebook_params)
    @notebook.save

    if request.xhr?
      render :json => @notebook
    end
  end

  def destroy
    @notebook = Notebook.find(params[:id])
    @notebook.destroy

    if request.xhr?
      render :json => @user.notebooks.all
    end
  end

  def update
    @notebook = Notebook.find(params[:id])

    if @notebook.update(notebook_params)
      if request.xhr?
        render :json => @user.notebooks.all
      end
    end
  end
end


private

  def set_user
    @user = current_user
  end

  def notebook_params
    params.permit(:name, :user_id)
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

before_action :set_notebook

  def update
    @page = @notebook.pages.find(params[:id])
    if @page.update(page_params)
      if request.xhr?
        render :json => {page: @page, list: params[:list]}
      end
    end
  end

  def destroy
    @page = @notebook.pages.find(params[:id])

    if @page.destroy
      if request.xhr?
        render :json => params[:list]
      end
    end

  end

  def create
    @page = @notebook.pages.new(page_params)
    @page.save
    @list = @page.lists.first
    @pages = @list.pages.all

    if request.xhr?
      render :json => {page: @page, pages: @pages, list: @list}
    end
  end
end


private

  def set_notebook
    @notebook = Notebook.find(params[:notebook_id])
  end

  def page_params
    params.permit(:name, :content, :list_ids => [])
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-copyright">
  <div class="container-fluid">
      © 2016 Copyright: Daniel Kent is Awesome | <%= link_to 'test elements', test_path %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FlexNotebook', root_path, {:class=>'navbar-brand'} %>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.email, user_path(current_user) %></li>
          <li><%= link_to "Log out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
        
      </ul>
    </div>
  </div>
</div>


app/views/layouts/_sidebar.html.erb
<aside>
  
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flexnotebook</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="wrapper">
    <body>
      <%= render "layouts/header" %>
      
      <div class='col-md-12'>
        <%= yield %>
      </div>      

      <%= render "layouts/footer" %>
    </body>
  </div>
  
</html>


app/views/lists/_form.html.erb
<%= form_for([@notebook, @list]) do |f| %>
  <fieldset>
    <ul>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="checkboxes">
        <%= f.label "What Pages do you want to include?" %>
        <%= f.collection_check_boxes :page_ids, @notebook.pages.all, :id, :name %>
      </li>
    </ul>
    <p>
      <%= f.submit %>
      <%= link_to "Back to #{@notebook.name}", @notebook, class: "button" %>
    </p>
  </fieldset>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing <%= @list.name %></h1>

<%= render "form" %>

app/views/lists/new.html.erb
<h1>Creating list for <%= @notebook.name %> notebook</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ol>
  <% if @pages %>
    <% @pages.each do |page| %>
      <li>
        <h2><%= link_to page.name, notebook_page_path(@notebook, page) %></h2>
      </li>
    <% end %>
  <% end %>
</ol>

<p>
  <%= link_to "Back to #{@notebook.name}", @notebook, class: "button" %>
  <%= link_to "Edit #{@list.name}", edit_notebook_list_path(@notebook, @list), class: "button" %>
  <%= link_to "Delete #{@list.name}", notebook_list_path(@notebook, @list), method: :delete, 
              data: { confirm: "Are you sure you want to delete #{@list.name}?" }, class: "button" %>
    
</p>

app/views/notebooks/index.html.erb

<%= react_component 'App', props = { 
    notebooks: @notebooks, 
    nav: @nav, 
    user: current_user
} %>

app/views/notebooks/main.html.erb
<h1><%= pluralize(@notebooks.count, "notebook") %></h1>

<ul>
  <% @notebooks.each do |n| %>
    <li>
      <article>
        <header>
          <h2><%= notebook.name %></h2>
        </header>
      </article>
    </li>
  <% end %>
</ul>

app/views/notebooks/show.html.erb
<h1><%= @notebook.name %></h1>

<ul>
  <% if @lists %>
    <% @lists.each do |list| %>
      <li>
        <h2><%= link_to list.name, notebook_list_path(@notebook, list) %></h2>
      </li>
    <% end %>
  <% end %>  
  <li>
    <h2>
      <%= link_to "All Pages", notebook_pages_path(@notebook) %> 
    </h2>
  </li>
</ul>

<div>
  <p>
    <%= link_to "New List", new_notebook_list_path(@notebook), class: "button" %>
    <%= link_to "New Page", new_notebook_page_path(@notebook), class: "button" %>
  </p>
</div>

app/views/pages/_form.html.erb
<%= form_for([@notebook, @page]) do |f| %>
  <fieldset>
    <ul>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li>
        <%= f.label :content %>
        <%= f.text_area :content %>
      </li>
      <li>
        <%= f.label "To which lists does this page belong?" %>
        <%= f.collection_check_boxes :list_ids, @notebook.lists.all, :id, :name %>
      </li>
    </ul>
    <p>
      <%= f.submit %>
      <%= link_to "Back to #{@notebook.name}", @notebook, class: "button" %>
    </p>
  </fieldset>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing <%= @page.name %></h1>

<%= render "form" %>

app/views/pages/index.html.erb
<h1>Pages for <%= @notebook.name %></h1>

<ul>
  <% @pages.each do |page| %>
    <li>
      <p>
        <%= link_to page.name, notebook_page_path(@notebook, page) %>
      </p>
    </li>
  <% end %>
</ul>

app/views/pages/new.html.erb
<h1>Create new page for <%= @notebook.name %></h1>

<%= render "form" %>

app/views/pages/show.html.erb

<article>
  <h1><%= @page.name %></h1>
  <p><%= @page.content %></p>    
</article>

<div>
  <p>
    <%= link_to "Back to #{@notebook.name}", @notebook, class: "button" %>
    <%= link_to "Edit", edit_notebook_page_path(@notebook, @page), class: "button" %>
    <%= link_to "Delete", notebook_page_path(@notebook, @page), method: :delete, 
                 data: { confirm: "Are you sure you want to delete #{@page.name}?" }, class: "button" %>
  </p>
</div>


app/views/users/show.html.erb
<h1>
  <%= @user.email %>
</h1>